package View;

import Controller.Dao;
import Model.*;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Medel Lozada
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    DefaultTableModel modelo;    
    public Admin() {
        initComponents();
        modelo = new DefaultTableModel();
        //Para poner al centro JPanel
        setLocationRelativeTo(null);
        setResizable(false);
        cargarCliente();  
        cargarSucursal();
        //Color JFrame
        this.getContentPane().setBackground(new Color(254,255,255));
    }
    
    
   public void Actualizar(){
        Usuario a= new Usuario();
        a.setUsuario(txt_usuario.getText());
        a.setPassword(txt_pass.getText());
        Dao.actUsuario(a);
        JOptionPane.showMessageDialog(null, "Usuario Actualizado");
    }
     
    public final  void cargarCliente(){
        for(Usuario a:Dao.listarUsuario()){                  
                  txt_usuario.setText(a.getUsuario());
                  txt_pass.setText(a.getPassword());
         }
    }
    
    public final  void cargarSucursal(){
        for(Sucursal a:Dao.listarSucursal()){                  
                  txt_nombreSucursal.setText(a.getNomSucursal());
                  txt_domicilio.setText(a.getDomicilio());
                  txt_telefono.setText(a.getTelefono());
                  //int valor2=Integer.parseInt(txt_cidr.getText());
         }
    }
    
   /* String[] titulos = {"Usuario", "Contraseña"};
    modelo = new DefaultTableModel(null, titulos);
    String[] fila = new String[2];
    
    for(Usuario a:Dao.listarUsuario()){                  
         fila[0]=a.getUsuario();
         fila[1]=a.getPassword();                  
         modelo.addRow(fila);
    }
    jtable_Usuario1.setModel(modelo);*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu = new javax.swing.JButton();
        btn_actUsuario = new javax.swing.JButton();
        txt_pass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombreSucursal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_domicilio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        btn_actEmpresa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        btn_menu.setBackground(new java.awt.Color(153, 153, 255));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home-house.png"))); // NOI18N
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_actUsuario.setBackground(new java.awt.Color(153, 153, 255));
        btn_actUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btn_actUsuario.setText("Actualizar");
        btn_actUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actUsuarioMouseClicked(evt);
            }
        });

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_passKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Contraseña");

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyTyped(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre de la empresa");

        txt_nombreSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreSucursalActionPerformed(evt);
            }
        });
        txt_nombreSucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreSucursalKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Domicilio");

        txt_domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_domicilioActionPerformed(evt);
            }
        });
        txt_domicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_domicilioKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });

        btn_actEmpresa.setBackground(new java.awt.Color(153, 153, 255));
        btn_actEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        btn_actEmpresa.setText("Actualizar");
        btn_actEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actEmpresaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_menu)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btn_actUsuario))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_nombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_actEmpresa))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_domicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_actUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_actEmpresa)
                .addGap(18, 18, 18)
                .addComponent(btn_menu)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        dispose();
        dashboardJFrame obj= new dashboardJFrame();
        obj.setVisible(true);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void txt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_usuarioKeyTyped

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
        /*
         for(Usuario a:Dao.listarUsuario()){                  
                  txt_usuario.setText(a.getUsuario());
         }*/
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        // TODO add your handling code here:       
    }//GEN-LAST:event_txt_passKeyTyped

    private void txt_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyReleased
        // TODO add your handling code here:    
    }//GEN-LAST:event_txt_passKeyReleased

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
               
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        // TODO add your handling code here:   
        
    }//GEN-LAST:event_txt_passKeyPressed

    private void btn_actUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actUsuarioMouseClicked
        // TODO add your handling code here:
       Actualizar();
    }//GEN-LAST:event_btn_actUsuarioMouseClicked

    private void txt_nombreSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreSucursalActionPerformed

    private void txt_nombreSucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreSucursalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreSucursalKeyTyped

    private void txt_domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_domicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_domicilioActionPerformed

    private void txt_domicilioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_domicilioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_domicilioKeyTyped

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        // TODO add your handling code here:
        char d= evt.getKeyChar();
        if(d < '0' || d > '9'){
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped

    private void btn_actEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actEmpresaMouseClicked
        // TODO add your handling code here:
        
        if (txt_nombreSucursal.getText().isEmpty() || txt_domicilio.getText().isEmpty() || txt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verefique sus datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            cargarSucursal();
        }/*else if(!txt_telefono.getText().matches("(\\+?[2-9]{2,3}\\-)?([2-9]{10})")){
            JOptionPane.showMessageDialog(null, "INGRESE UN NUMERO DE TELEFONO REAL");
            cargarSucursal();
        }*/
        else{
        try{
        Sucursal a= new Sucursal();
        a.setNomSucursal(txt_nombreSucursal.getText());
        a.setDomicilio(txt_domicilio.getText());
        a.setTelefono(txt_telefono.getText());
        Dao.actSucursal(a);
        JOptionPane.showMessageDialog(null, "Sucursal Actualizado");
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_actEmpresaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actEmpresa;
    private javax.swing.JButton btn_actUsuario;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_domicilio;
    private javax.swing.JTextField txt_nombreSucursal;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
