/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;

/**
 *
 * @author Miguel Medel Lozada
 */
public class dashboardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form dashboardJFrame
     */
    public dashboardJFrame() {
        initComponents();
        //Para poner al centro JPanel
        this.getContentPane().setBackground(new Color(0,0,255));
        setLocationRelativeTo(null);
        setResizable(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_usuario = new javax.swing.JButton();
        btn_empleado = new javax.swing.JButton();
        btn_Pedido = new javax.swing.JButton();
        btn_producto1 = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/configure.png"))); // NOI18N
        btn_usuario.setText("Configurar");
        btn_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 160, 40));

        btn_empleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/man-employee.png"))); // NOI18N
        btn_empleado.setText("Empleado");
        btn_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 160, 40));

        btn_Pedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/shopping_cart_.png"))); // NOI18N
        btn_Pedido.setText("Pedido");
        btn_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 40));

        btn_producto1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_producto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/food.png"))); // NOI18N
        btn_producto1.setText("Producto");
        btn_producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_producto1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 160, 40));

        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sales_.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ima01.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuarioActionPerformed
        dispose();
        Admin obj= new Admin();
        obj.setVisible(true);
        
    }//GEN-LAST:event_btn_usuarioActionPerformed

    private void btn_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PedidoActionPerformed
        dispose();
        ClienteJFrame pro=new ClienteJFrame();
        pro.setVisible(true);
        
    }//GEN-LAST:event_btn_PedidoActionPerformed

    private void btn_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadoActionPerformed
        dispose();
        EmpleadoFrame emp=new EmpleadoFrame();
        emp.setVisible(true);
        
    }//GEN-LAST:event_btn_empleadoActionPerformed

    private void btn_producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_producto1ActionPerformed
        dispose();
        ProductoJFrame pe=new ProductoJFrame();
        pe.setVisible(true);
        
    }//GEN-LAST:event_btn_producto1ActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        dispose();
        VentasJFrame pe=new VentasJFrame();
        pe.setVisible(true);
        
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btn_Pedido;
    private javax.swing.JButton btn_empleado;
    private javax.swing.JButton btn_producto1;
    private javax.swing.JButton btn_usuario;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
