/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.*;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Medel Lozada
 */
public class PedidoJFrame extends javax.swing.JFrame {
   
    /**
     * Creates new form PedidoJFrame
     */
    public PedidoJFrame() {
        initComponents();
         //Para poner al centro JPanel
        setLocationRelativeTo(null);
        setResizable(false);         
        cargarJCombo();
        cargarDatosTabla();
        cargarJlabelCliente();
        cargarJlabelFactura();               
        //Color JFrame
        this.getContentPane().setBackground(new Color(254,255,255));
    }
    
    void cargarJlabelFactura(){
        Object row[] = new Object[1];
        for(Factura a:Dao.MostrarUltimaFactura()){                          
            row[0]=a.getIdFactura();
        }
        jLabel_idFactura.setText(row[0].toString());        
    }
    
    void cargarJlabelCliente(){
        Object row[] = new Object[3];
        for(Cliente a:Dao.MostrarCliente()){                          
            row[0]=a.getIdCliente();
            row[1]=a.getNombreCliente();
            row[2]=a.getTelefono();                       
        }
        jLabelIdCliente.setText(row[0].toString());
        jLabelNombre.setText(row[1].toString());
        jLabelTel.setText(row[2].toString());
    }
     void cargarJCombo(){           
        ArrayList<Categoria>lista=Dao.listarCategoria();
       for(int x=0;x<lista.size();x++){
           Categoria obj=new Categoria(lista.get(x).getIdCategoria(),lista.get(x).getNomCategoria());           
           jComboCategoria.addItem(obj);
       }
       }
     
      void cargarDatosTabla(){
          jTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
         jTable.getTableHeader().setOpaque(false);         
         jTable.getTableHeader().setBackground(new Color(32,136,203));
         jTable.getTableHeader().setForeground(new Color(00,00,00));
           String[] titulos = {"ID","Producto","Cantidad","Precio"};
           DefaultTableModel modelo= new DefaultTableModel(null, titulos);
           jTable.setModel(modelo);
           cargarJlabelCliente();
           String idCliente=jLabelIdCliente.getText().toString();
           Dao my=new Dao();
           Detalle vo= new Detalle();
           ArrayList<Detalle>lista=my.getDetalle(idCliente);
         for(int i=0;i<lista.size();i++){              
            Object fila[] = new Object[4];
            vo = lista.get(i);
            fila[0]=vo.getProducto_id();
            fila[1]=vo.getProducto_nombre();
            fila[2]=vo.getCantidad();
            fila[3]=vo.getPrecio();            
             modelo.addRow(fila);
        }
        jTable.setModel(modelo);          
    }
      
       void limpiarDatos(){
        txt_nombre.setText("");
        txt_Precio.setText("");        
        txt_id.setText("");
        jSpinner.setValue(0);
    }
     
    public void getIdDetalle(){        
        JFrame IdDetalle=new TicketJFr();
        IdDetalle.setVisible(true);
        dispose();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        btn_siguiente = new javax.swing.JButton();
        jComboCategoria = new javax.swing.JComboBox();
        jSpinner = new javax.swing.JSpinner();
        txt_id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelIdCliente = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JLabel();
        txt_Precio = new javax.swing.JLabel();
        jLabel_idFactura = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProducto.setFocusable(false);
        jTableProducto.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTableProducto.setRowHeight(25);
        jTableProducto.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jTableProducto.setShowVerticalLines(false);
        jTableProducto.getTableHeader().setReorderingAllowed(false);
        jTableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProducto);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable.setRowHeight(25);
        jTable.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jTable.setShowVerticalLines(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        btn_agregar.setBackground(new java.awt.Color(153, 153, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ic_input_add.png"))); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_siguiente.setBackground(new java.awt.Color(153, 153, 255));
        btn_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        jComboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaActionPerformed(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cliente:");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(51, 0, 255));
        jLabelNombre.setText("jLabel2");

        jLabelIdCliente.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jLabelIdCliente.setText("jLabel2");

        jLabelTel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTel.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Telefono:");

        txt_nombre.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(0, 0, 255));

        txt_Precio.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        txt_Precio.setForeground(new java.awt.Color(0, 0, 255));

        jLabel_idFactura.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jLabel_idFactura.setText("jLabel3");

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ic_delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIdCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_idFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_siguiente)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_id)
                            .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_agregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_eliminar))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jComboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre)
                    .addComponent(txt_Precio)
                    .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar))
                .addGap(13, 13, 13)
                .addComponent(txt_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabel1)
                    .addComponent(jLabelTel)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdCliente)
                            .addComponent(jLabel_idFactura))
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_siguiente)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaActionPerformed
        // TODO add your handling code here:        
        Categoria add=(Categoria)jComboCategoria.getSelectedItem();
        String id=add.getIdCategoria();        
        Dao my=new Dao();
        ArrayList<Producto>lista=my.getData(id);
        String[] titulos = {"ID","Nombre","Precio"};
        DefaultTableModel modelo= new DefaultTableModel(null, titulos);
        String[] fila = new String[3];
         for(int i=0;i<lista.size();i++){              
            fila[0]=lista.get(i).getIdProducto();
            fila[1]=lista.get(i).getNomProducto();
            fila[2]=lista.get(i).getPrecio();
             modelo.addRow(fila);
        }
        jTableProducto.setModel(modelo);
    }//GEN-LAST:event_jComboCategoriaActionPerformed

    private void jTableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoMouseClicked
        // TODO add your handling code here:
        String id =(String)jTableProducto.getValueAt(jTableProducto.getSelectedRow(),0);      
        String nombre =(String)jTableProducto.getValueAt(jTableProducto.getSelectedRow(),1);      
        String precio =(String)jTableProducto.getValueAt(jTableProducto.getSelectedRow(),2);      
        
        txt_id.setText(id);
        txt_nombre.setText(nombre);
        txt_Precio.setText(precio);
        btn_eliminar.setEnabled(false);
        btn_agregar.setEnabled(true);
    }//GEN-LAST:event_jTableProductoMouseClicked

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
         if (txt_nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Verefique sus datos", "ERROR", JOptionPane.ERROR_MESSAGE);           
        }
        else{
        try{
            int value = (Integer)jSpinner.getValue();           
            int cantidad=value;             
                int precio=Integer.parseInt(txt_Precio.getText());
            int totalProducto=precio*cantidad;                
            Detalle a= new Detalle();
            a.setNum_detalle(jLabelIdCliente.getText());
            a.setFactura_id(jLabel_idFactura.getText());
            a.setProducto_id(txt_id.getText());
            a.setCantidad(Integer.toString(cantidad));
            a.setPrecio(Integer.toString(totalProducto));
            Dao.registrarDatalle(a);
            cargarJlabelCliente();
           limpiarDatos();
           cargarDatosTabla();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:       
        getIdDetalle();
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        try{
        Detalle a= new Detalle();                
        a.setNum_detalle(jLabelIdCliente.getText());
        a.setProducto_id(txt_id.getText());  
        
        Dao.eliDetalle(a);
        JOptionPane.showMessageDialog(null, "Producto Eliminado");
        limpiarDatos();
        cargarDatosTabla();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        String id =(String)jTable.getValueAt(jTable.getSelectedRow(),0);      
        String nombre =(String)jTable.getValueAt(jTable.getSelectedRow(),1);      
        String precio =(String)jTable.getValueAt(jTable.getSelectedRow(),3);      
        
        txt_id.setText(id);
        txt_nombre.setText(nombre);
        txt_Precio.setText(precio);
        btn_agregar.setEnabled(false);     
        btn_eliminar.setEnabled(true);
    }//GEN-LAST:event_jTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JComboBox jComboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIdCliente;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabel_idFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTableProducto;
    private javax.swing.JLabel txt_Precio;
    private javax.swing.JLabel txt_id;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration//GEN-END:variables
}
