package View;
import Controller.Dao;
import Model.Caja;
import Model.Cliente;
import Model.Detalle;
import codigo.GenerarCodigos;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TicketJFr extends javax.swing.JFrame {

    /**
     * Creates new form TicketJFr
     */
    public TicketJFr() {
        initComponents();
         //Para poner al centro JPanel
        setLocationRelativeTo(null);
        setResizable(false); 
        cargarJlabelCliente();
        agregarNumeroTicket();
        cargarSubTotal();
        //Color JFrame
        this.getContentPane().setBackground(new Color(254,255,255));
    }
   
    void cargarJlabelCliente(){
        Object row[] = new Object[3];
        for(Cliente a:Dao.MostrarCliente()){                          
            row[0]=a.getIdCliente();
            row[1]=a.getNombreCliente();
            row[2]=a.getTelefono();  
        }
        txt_detalleID.setText(row[0].toString());        
    }
    
    void agregarNumeroTicket(){       
        String c="";
        int j=0;
        Object row[] = new Object[1];
        for(Caja a:Dao.idUltimoCaja()){                          
            row[0]=a.getNum_ticket();                          
        }   
        if(row[0]==null){
                row[0]=00000001;
            } 
        //jLabelIdCliente.setText(row[0].toString());
         c=row[0].toString();        
        
        if(c==null){
            txt_numTicket.setText("00000001");
        }else{
            j=Integer.parseInt(c);
            GenerarCodigos gen= new GenerarCodigos();
            gen.generar(j);
            txt_numTicket.setText(gen.serie());
        }
    }
    
    void cargarSubTotal(){
        //txt_detalleID.setText(row[0].toString());        
        Object row[] = new Object[1];
        String idCliente=txt_detalleID.getText().toString();

         for(Detalle a:Dao.getSubTotal(idCliente)){              
            row[0]=a.getPrecio();
        }
         txt_Subtotal.setText(row[0].toString());
         
         //carga de datos tabla
          String[] titulos = {"ID","Producto","Cantidad","Precio"};
           DefaultTableModel modelo= new DefaultTableModel(null, titulos);
           jTable.setModel(modelo);
           cargarJlabelCliente();
           
           Dao my=new Dao();
           Detalle vo= new Detalle();
           ArrayList<Detalle>lista=my.getDetalle(idCliente);
         for(int i=0;i<lista.size();i++){              
            Object fila[] = new Object[4];
            vo = lista.get(i);
            fila[0]=vo.getProducto_id();
            fila[1]=vo.getProducto_nombre();
            fila[2]=vo.getCantidad();
            fila[3]=vo.getPrecio();            
             modelo.addRow(fila);
        }
        jTable.setModel(modelo);          
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_numTicket = new javax.swing.JLabel();
        txt_detalleID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_ventaTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_efectivo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        txt_cambio = new javax.swing.JLabel();
        txt_iva = new javax.swing.JTextField();
        btnFinalizar = new javax.swing.JButton();
        txt_Subtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TICKET");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subtotal");

        txt_numTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numTicket.setForeground(new java.awt.Color(255, 0, 0));
        txt_numTicket.setText("jLabel8");

        txt_detalleID.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        txt_detalleID.setText("jLabel8");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Impuesto(IVA)");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back_arrow_11236.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_ventaTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ventaTotal.setForeground(new java.awt.Color(0, 153, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Venta Total");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Efectivo");

        txt_efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_efectivoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_efectivoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cambio");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable);

        txt_cambio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txt_iva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ivaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ivaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ivaKeyTyped(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(153, 153, 255));
        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/finalindicator_5070.png"))); // NOI18N
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        txt_Subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Subtotal.setForeground(new java.awt.Color(51, 51, 255));
        txt_Subtotal.setText("jL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_numTicket)
                        .addGap(56, 56, 56)
                        .addComponent(txt_detalleID))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ventaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Subtotal)
                        .addGap(53, 53, 53)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_iva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Subtotal))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txt_ventaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_detalleID))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txt_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_numTicket))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnFinalizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PedidoJFrame pro=new PedidoJFrame();
        pro.setVisible(true);
        dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_efectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efectivoKeyTyped
     char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) 
        && (caracter != KeyEvent.VK_BACK_SPACE)
        && (caracter != '.' || txt_efectivo.getText().contains(".")) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_efectivoKeyTyped

    private void txt_ivaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyPressed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_txt_ivaKeyPressed

    private void txt_ivaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyReleased
        // TODO add your handling code here:
        int valor=0;        
        String sr=valor+txt_iva.getText();        
        double sum=Double.parseDouble(sr);
        int precio=Integer.parseInt(txt_Subtotal.getText());        
        double total=precio+sum;
        txt_ventaTotal.setText(Double.toString(total));
    }//GEN-LAST:event_txt_ivaKeyReleased

    private void txt_efectivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_efectivoKeyReleased
        // TODO add your handling code here:
        int valor=0;        
        String sr=valor+txt_efectivo.getText();
        double efectivo=Double.parseDouble(sr);
        double  total=Double.parseDouble(txt_ventaTotal.getText());
        double cambio=efectivo-total;        
        
        txt_cambio.setText(Double.toString((double)Math.round(cambio*100d)/100d));
    }//GEN-LAST:event_txt_efectivoKeyReleased

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
         if (txt_iva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Igrese Impuesto(IVA)", "ERROR", JOptionPane.ERROR_MESSAGE);           
        }else if (txt_efectivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Igrese efectivo", "ERROR", JOptionPane.ERROR_MESSAGE);           
        }
        else{
        try{
            Caja a= new Caja();
            a.setNum_ticket(txt_numTicket.getText());
            a.setSubtotal(txt_Subtotal.getText());
            a.setIva(txt_iva.getText());
            a.setVentaTotal(txt_ventaTotal.getText());
            a.setEfectivo(txt_efectivo.getText());
            a.setCambio(txt_cambio.getText());
            a.setDetalle_id(txt_detalleID.getText());
            
            Dao.registrarCaja(a);
            
            VentasJFrame obj= new VentasJFrame();
            obj.setVisible(true);
            dispose();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
        }
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void txt_ivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ivaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) 
        && (caracter != KeyEvent.VK_BACK_SPACE)
        && (caracter != '.' || txt_iva.getText().contains(".")) ) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_ivaKeyTyped

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel txt_Subtotal;
    private javax.swing.JLabel txt_cambio;
    private javax.swing.JLabel txt_detalleID;
    private javax.swing.JTextField txt_efectivo;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JLabel txt_numTicket;
    private javax.swing.JLabel txt_ventaTotal;
    // End of variables declaration//GEN-END:variables
}
