/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Medel Lozada
 */
public class VentasJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VentasJFrame
     */
    public VentasJFrame() {
        initComponents();
        //Para poner al centro JPanel
        setLocationRelativeTo(null);
        setResizable(false); 
        cargarDatosTabla();
        //Color JFrame
        this.getContentPane().setBackground(new Color(254,255,255));
        
        txt_numTicket.setEnabled(false);        
        txt_nombre.setEnabled(false);        
        txt_ventaTotal.setEnabled(false); 
    }

    void cargarDatosTabla(){
        //carga de datos tabla
        jTable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
         jTable.getTableHeader().setOpaque(false);         
         jTable.getTableHeader().setBackground(new Color(32,136,203));
         jTable.getTableHeader().setForeground(new Color(00,00,00));
          String[] titulos = {"#","Cliente","Fecha","Hora","Total"};
           DefaultTableModel modelo= new DefaultTableModel(null, titulos);
           jTable.setModel(modelo);
         Object row[] = new Object[5];   
         for(Caja a:Dao.mostrarCaja()){              
            row[0]=a.getNum_ticket();
            row[1]=a.getNomCliente();
            row[2]=a.getFecha();
            row[3]=a.getHora();
            row[4]=a.getVentaTotal();
            
            modelo.addRow(row);
        }
        jTable.setModel(modelo);          
        //Muestra suma total de las ventas        
        Object a[] = new Object[5];   
        for(Caja c:Dao.sumaTotalCaja()){
            a[0]=c.getVentaTotal();            
        }
        txt_total.setText(a[0].toString());
        
        //Muestra ventas realizadas
        for(Caja c:Dao.sumaVentasRealizadasCaja()){
            a[1]=c.getNum_ticket();
        }
        txt_ventas.setText(a[1].toString());
        //muestra el total de productos
        Object pro[] = new Object[2];   
        for(Producto p:Dao.TotalProducto()){
            pro[0]=p.getIdProducto();
        }
        txtTotalProductos.setText(pro[0].toString());
        //muestra el total empleado
        for(Empleado em:Dao.TotalEmpleado()){
            pro[1]=em.getIdEmpleado();
        }
        txtTotalEmpleado.setText(pro[1].toString());
    }
     public void limpiarDatos(){
        txt_numTicket.setText("");
        txt_nombre.setText("");
        txt_ventaTotal.setText("");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_menu1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_total = new javax.swing.JLabel();
        txt_numTicket = new javax.swing.JLabel();
        txt_ventaTotal = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_tabla = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_ventas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalProductos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_ventanaProducto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTotalEmpleado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnVentanaEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_menu1.setBackground(new java.awt.Color(153, 153, 255));
        btn_menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/home-house.png"))); // NOI18N
        btn_menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu1ActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.setFocusable(false);
        jTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable.setRowHeight(25);
        jTable.setSelectionBackground(new java.awt.Color(0, 255, 0));
        jTable.setShowVerticalLines(false);
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL VENDIDO");

        txt_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_total.setText("jLabel2");

        txt_numTicket.setBackground(new java.awt.Color(204, 0, 51));
        txt_numTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numTicket.setText("#");

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 255));
        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ic_delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        btn_buscar.setBackground(new java.awt.Color(153, 153, 255));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loupe_78956.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_tabla.setBackground(new java.awt.Color(153, 153, 255));
        btn_tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/table_1061.png"))); // NOI18N
        btn_tabla.setText("tabla");
        btn_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("VENTAS REALIZADAS ");

        txt_ventas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ventas.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("HAY");

        txtTotalProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalProductos.setText("jLab");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("PRODUCTOS");

        btn_ventanaProducto.setBackground(new java.awt.Color(153, 153, 255));
        btn_ventanaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/artboard.png"))); // NOI18N
        btn_ventanaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventanaProductoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("HAY");

        txtTotalEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalEmpleado.setText("jLa");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("EMPLEADOS");

        btnVentanaEmpleados.setBackground(new java.awt.Color(153, 153, 255));
        btnVentanaEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/artboard.png"))); // NOI18N
        btnVentanaEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ventas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_total)
                        .addGap(118, 118, 118))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_numTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ventaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tabla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalProductos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ventanaProducto)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalEmpleado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVentanaEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_menu1)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numTicket)
                    .addComponent(txt_ventaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(btn_tabla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_total)
                    .addComponent(jLabel2)
                    .addComponent(txt_ventas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTotalProductos)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtTotalEmpleado)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_menu1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVentanaEmpleados)
                            .addComponent(btn_ventanaProducto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu1ActionPerformed
        // TODO add your handling code here:
        dispose();
        dashboardJFrame obj= new dashboardJFrame();
        obj.setVisible(true);
    }//GEN-LAST:event_btn_menu1ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        String id =(String)jTable.getValueAt(jTable.getSelectedRow(),0);
        String nombre =(String)jTable.getValueAt(jTable.getSelectedRow(),1);
        String total =(String)jTable.getValueAt(jTable.getSelectedRow(),4);
        txt_numTicket.setText(id);
        txt_nombre.setText(nombre);
        txt_ventaTotal.setText(total);       
    }//GEN-LAST:event_jTableMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try{
        Caja a= new Caja();                
        a.setNum_ticket(txt_numTicket.getText());                
        Dao.eliCaja(a);        
        limpiarDatos();
        cargarDatosTabla();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try{
            String[] titulos = {"#","Cliente","Fecha","Hora","Total"};
           DefaultTableModel modelo= new DefaultTableModel(null, titulos);
           jTable.setModel(modelo);
        Object row[] = new Object[5];   
         String valor=txt_buscar.getText();
           
        for(Caja a:Dao.buscarCaja(valor)){              
            row[0]=a.getNum_ticket();
            row[1]=a.getNomCliente();
            row[2]=a.getFecha();
            row[3]=a.getHora();
            row[4]=a.getVentaTotal();                        
            modelo.addRow(row);
        }        
        jTable.setModel(modelo);
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablaActionPerformed
        cargarDatosTabla();
        txt_buscar.setText("");
    }//GEN-LAST:event_btn_tablaActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
    
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void btn_ventanaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventanaProductoActionPerformed
        ProductoJFrame pe=new ProductoJFrame();
        pe.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ventanaProductoActionPerformed

    private void btnVentanaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaEmpleadosActionPerformed
        EmpleadoFrame emp=new EmpleadoFrame();
        emp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVentanaEmpleadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVentanaEmpleados;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_menu1;
    private javax.swing.JButton btn_tabla;
    private javax.swing.JButton btn_ventanaProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel txtTotalEmpleado;
    private javax.swing.JLabel txtTotalProductos;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JLabel txt_numTicket;
    private javax.swing.JLabel txt_total;
    private javax.swing.JTextField txt_ventaTotal;
    private javax.swing.JLabel txt_ventas;
    // End of variables declaration//GEN-END:variables
}
